name: Docker Image CI Main

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-push:
    # runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.dockerize.ir
          username: admin
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build frontend image
        run: docker build -f etl_frontend/Dockerfile -t registry.dockerize.ir/${{ github.repository }}/frontend:$(date +%Y%m%d%H%M%S) ./frontend

      - name: Push frontend image
        run: docker push registry.dockerize.ir/${{ github.repository }}/frontend:$(date +%Y%m%d%H%M%S)

      - name: Build backend image
        run: docker build -f etl-server/Dockerfile -t registry.dockerize.ir/${{ github.repository }}/backend:$(date +%Y%m%d%H%M%S) ./backend

      - name: Push backend image
        run: docker push registry.dockerize.ir/${{ github.repository }}/backend:$(date +%Y%m%d%H%M%S)
